// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RZWRITEFLATBUFFERS_IMAGE_METADATAS_H_
#define FLATBUFFERS_GENERATED_RZWRITEFLATBUFFERS_IMAGE_METADATAS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace Image {
namespace Metadatas {

struct Picture;
struct PictureBuilder;

struct Exif;
struct ExifBuilder;

struct Iptc;
struct IptcBuilder;

struct Xmp;
struct XmpBuilder;

struct Picture FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PictureBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FILE_NAME = 4,
    VT_FILESIZE = 6,
    VT_FILESIZE_X = 8,
    VT_FILESIZE_Y = 10,
    VT_FILEPATH = 12,
    VT_EXIFDATA = 14,
    VT_IPTCDATA = 16,
    VT_XMPDATA = 18
  };
  const ::flatbuffers::String *file_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILE_NAME);
  }
  float filesize() const {
    return GetField<float>(VT_FILESIZE, 0.0f);
  }
  float filesize_x() const {
    return GetField<float>(VT_FILESIZE_X, 0.0f);
  }
  float filesize_y() const {
    return GetField<float>(VT_FILESIZE_Y, 0.0f);
  }
  const ::flatbuffers::String *filepath() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILEPATH);
  }
  const Image::Metadatas::Exif *exifdata() const {
    return GetPointer<const Image::Metadatas::Exif *>(VT_EXIFDATA);
  }
  const Image::Metadatas::Iptc *iptcdata() const {
    return GetPointer<const Image::Metadatas::Iptc *>(VT_IPTCDATA);
  }
  const Image::Metadatas::Xmp *xmpdata() const {
    return GetPointer<const Image::Metadatas::Xmp *>(VT_XMPDATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FILE_NAME) &&
           verifier.VerifyString(file_name()) &&
           VerifyField<float>(verifier, VT_FILESIZE, 4) &&
           VerifyField<float>(verifier, VT_FILESIZE_X, 4) &&
           VerifyField<float>(verifier, VT_FILESIZE_Y, 4) &&
           VerifyOffset(verifier, VT_FILEPATH) &&
           verifier.VerifyString(filepath()) &&
           VerifyOffset(verifier, VT_EXIFDATA) &&
           verifier.VerifyTable(exifdata()) &&
           VerifyOffset(verifier, VT_IPTCDATA) &&
           verifier.VerifyTable(iptcdata()) &&
           VerifyOffset(verifier, VT_XMPDATA) &&
           verifier.VerifyTable(xmpdata()) &&
           verifier.EndTable();
  }
};

struct PictureBuilder {
  typedef Picture Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_file_name(::flatbuffers::Offset<::flatbuffers::String> file_name) {
    fbb_.AddOffset(Picture::VT_FILE_NAME, file_name);
  }
  void add_filesize(float filesize) {
    fbb_.AddElement<float>(Picture::VT_FILESIZE, filesize, 0.0f);
  }
  void add_filesize_x(float filesize_x) {
    fbb_.AddElement<float>(Picture::VT_FILESIZE_X, filesize_x, 0.0f);
  }
  void add_filesize_y(float filesize_y) {
    fbb_.AddElement<float>(Picture::VT_FILESIZE_Y, filesize_y, 0.0f);
  }
  void add_filepath(::flatbuffers::Offset<::flatbuffers::String> filepath) {
    fbb_.AddOffset(Picture::VT_FILEPATH, filepath);
  }
  void add_exifdata(::flatbuffers::Offset<Image::Metadatas::Exif> exifdata) {
    fbb_.AddOffset(Picture::VT_EXIFDATA, exifdata);
  }
  void add_iptcdata(::flatbuffers::Offset<Image::Metadatas::Iptc> iptcdata) {
    fbb_.AddOffset(Picture::VT_IPTCDATA, iptcdata);
  }
  void add_xmpdata(::flatbuffers::Offset<Image::Metadatas::Xmp> xmpdata) {
    fbb_.AddOffset(Picture::VT_XMPDATA, xmpdata);
  }
  explicit PictureBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Picture> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Picture>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Picture> CreatePicture(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> file_name = 0,
    float filesize = 0.0f,
    float filesize_x = 0.0f,
    float filesize_y = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> filepath = 0,
    ::flatbuffers::Offset<Image::Metadatas::Exif> exifdata = 0,
    ::flatbuffers::Offset<Image::Metadatas::Iptc> iptcdata = 0,
    ::flatbuffers::Offset<Image::Metadatas::Xmp> xmpdata = 0) {
  PictureBuilder builder_(_fbb);
  builder_.add_xmpdata(xmpdata);
  builder_.add_iptcdata(iptcdata);
  builder_.add_exifdata(exifdata);
  builder_.add_filepath(filepath);
  builder_.add_filesize_y(filesize_y);
  builder_.add_filesize_x(filesize_x);
  builder_.add_filesize(filesize);
  builder_.add_file_name(file_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Picture> CreatePictureDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *file_name = nullptr,
    float filesize = 0.0f,
    float filesize_x = 0.0f,
    float filesize_y = 0.0f,
    const char *filepath = nullptr,
    ::flatbuffers::Offset<Image::Metadatas::Exif> exifdata = 0,
    ::flatbuffers::Offset<Image::Metadatas::Iptc> iptcdata = 0,
    ::flatbuffers::Offset<Image::Metadatas::Xmp> xmpdata = 0) {
  auto file_name__ = file_name ? _fbb.CreateString(file_name) : 0;
  auto filepath__ = filepath ? _fbb.CreateString(filepath) : 0;
  return Image::Metadatas::CreatePicture(
      _fbb,
      file_name__,
      filesize,
      filesize_x,
      filesize_y,
      filepath__,
      exifdata,
      iptcdata,
      xmpdata);
}

struct Exif FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ExifBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FILE_NAME = 4,
    VT_GPSTAG = 6,
    VT_IMAGEDESCRIPTION = 8,
    VT_GPSLONGITUDEREF = 10,
    VT_GPSMAPDATUM = 12,
    VT_IMAGEUNIQUEID = 14,
    VT_IMAGEID = 16,
    VT_GPSLATITUDEREF = 18,
    VT_USERCOMMENT = 20,
    VT_GPSALTITUDE = 22,
    VT_DOCUMENTNAME = 24,
    VT_GPSTIMESTAMP = 26,
    VT_COPYRIGHT = 28,
    VT_GPSALTITUDEREF = 30,
    VT_GPSDATESTAMP = 32,
    VT_GPSLONGITUDE = 34,
    VT_GPSLATITUDE = 36,
    VT_DATETIMEORIGINAL = 38,
    VT_SECURITYCLASSIFICATION = 40
  };
  const ::flatbuffers::String *file_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILE_NAME);
  }
  const ::flatbuffers::String *gpstag() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GPSTAG);
  }
  const ::flatbuffers::String *imagedescription() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IMAGEDESCRIPTION);
  }
  const ::flatbuffers::String *gpslongituderef() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GPSLONGITUDEREF);
  }
  const ::flatbuffers::String *gpsmapdatum() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GPSMAPDATUM);
  }
  const ::flatbuffers::String *imageuniqueid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IMAGEUNIQUEID);
  }
  const ::flatbuffers::String *imageid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IMAGEID);
  }
  const ::flatbuffers::String *gpslatituderef() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GPSLATITUDEREF);
  }
  const ::flatbuffers::String *usercomment() const {
    return GetPointer<const ::flatbuffers::String *>(VT_USERCOMMENT);
  }
  const ::flatbuffers::String *gpsaltitude() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GPSALTITUDE);
  }
  const ::flatbuffers::String *documentname() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DOCUMENTNAME);
  }
  const ::flatbuffers::String *gpstimestamp() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GPSTIMESTAMP);
  }
  const ::flatbuffers::String *copyright() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COPYRIGHT);
  }
  const ::flatbuffers::String *gpsaltituderef() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GPSALTITUDEREF);
  }
  const ::flatbuffers::String *gpsdatestamp() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GPSDATESTAMP);
  }
  const ::flatbuffers::String *gpslongitude() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GPSLONGITUDE);
  }
  const ::flatbuffers::String *gpslatitude() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GPSLATITUDE);
  }
  const ::flatbuffers::String *datetimeoriginal() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATETIMEORIGINAL);
  }
  const ::flatbuffers::String *securityclassification() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SECURITYCLASSIFICATION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FILE_NAME) &&
           verifier.VerifyString(file_name()) &&
           VerifyOffset(verifier, VT_GPSTAG) &&
           verifier.VerifyString(gpstag()) &&
           VerifyOffset(verifier, VT_IMAGEDESCRIPTION) &&
           verifier.VerifyString(imagedescription()) &&
           VerifyOffset(verifier, VT_GPSLONGITUDEREF) &&
           verifier.VerifyString(gpslongituderef()) &&
           VerifyOffset(verifier, VT_GPSMAPDATUM) &&
           verifier.VerifyString(gpsmapdatum()) &&
           VerifyOffset(verifier, VT_IMAGEUNIQUEID) &&
           verifier.VerifyString(imageuniqueid()) &&
           VerifyOffset(verifier, VT_IMAGEID) &&
           verifier.VerifyString(imageid()) &&
           VerifyOffset(verifier, VT_GPSLATITUDEREF) &&
           verifier.VerifyString(gpslatituderef()) &&
           VerifyOffset(verifier, VT_USERCOMMENT) &&
           verifier.VerifyString(usercomment()) &&
           VerifyOffset(verifier, VT_GPSALTITUDE) &&
           verifier.VerifyString(gpsaltitude()) &&
           VerifyOffset(verifier, VT_DOCUMENTNAME) &&
           verifier.VerifyString(documentname()) &&
           VerifyOffset(verifier, VT_GPSTIMESTAMP) &&
           verifier.VerifyString(gpstimestamp()) &&
           VerifyOffset(verifier, VT_COPYRIGHT) &&
           verifier.VerifyString(copyright()) &&
           VerifyOffset(verifier, VT_GPSALTITUDEREF) &&
           verifier.VerifyString(gpsaltituderef()) &&
           VerifyOffset(verifier, VT_GPSDATESTAMP) &&
           verifier.VerifyString(gpsdatestamp()) &&
           VerifyOffset(verifier, VT_GPSLONGITUDE) &&
           verifier.VerifyString(gpslongitude()) &&
           VerifyOffset(verifier, VT_GPSLATITUDE) &&
           verifier.VerifyString(gpslatitude()) &&
           VerifyOffset(verifier, VT_DATETIMEORIGINAL) &&
           verifier.VerifyString(datetimeoriginal()) &&
           VerifyOffset(verifier, VT_SECURITYCLASSIFICATION) &&
           verifier.VerifyString(securityclassification()) &&
           verifier.EndTable();
  }
};

struct ExifBuilder {
  typedef Exif Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_file_name(::flatbuffers::Offset<::flatbuffers::String> file_name) {
    fbb_.AddOffset(Exif::VT_FILE_NAME, file_name);
  }
  void add_gpstag(::flatbuffers::Offset<::flatbuffers::String> gpstag) {
    fbb_.AddOffset(Exif::VT_GPSTAG, gpstag);
  }
  void add_imagedescription(::flatbuffers::Offset<::flatbuffers::String> imagedescription) {
    fbb_.AddOffset(Exif::VT_IMAGEDESCRIPTION, imagedescription);
  }
  void add_gpslongituderef(::flatbuffers::Offset<::flatbuffers::String> gpslongituderef) {
    fbb_.AddOffset(Exif::VT_GPSLONGITUDEREF, gpslongituderef);
  }
  void add_gpsmapdatum(::flatbuffers::Offset<::flatbuffers::String> gpsmapdatum) {
    fbb_.AddOffset(Exif::VT_GPSMAPDATUM, gpsmapdatum);
  }
  void add_imageuniqueid(::flatbuffers::Offset<::flatbuffers::String> imageuniqueid) {
    fbb_.AddOffset(Exif::VT_IMAGEUNIQUEID, imageuniqueid);
  }
  void add_imageid(::flatbuffers::Offset<::flatbuffers::String> imageid) {
    fbb_.AddOffset(Exif::VT_IMAGEID, imageid);
  }
  void add_gpslatituderef(::flatbuffers::Offset<::flatbuffers::String> gpslatituderef) {
    fbb_.AddOffset(Exif::VT_GPSLATITUDEREF, gpslatituderef);
  }
  void add_usercomment(::flatbuffers::Offset<::flatbuffers::String> usercomment) {
    fbb_.AddOffset(Exif::VT_USERCOMMENT, usercomment);
  }
  void add_gpsaltitude(::flatbuffers::Offset<::flatbuffers::String> gpsaltitude) {
    fbb_.AddOffset(Exif::VT_GPSALTITUDE, gpsaltitude);
  }
  void add_documentname(::flatbuffers::Offset<::flatbuffers::String> documentname) {
    fbb_.AddOffset(Exif::VT_DOCUMENTNAME, documentname);
  }
  void add_gpstimestamp(::flatbuffers::Offset<::flatbuffers::String> gpstimestamp) {
    fbb_.AddOffset(Exif::VT_GPSTIMESTAMP, gpstimestamp);
  }
  void add_copyright(::flatbuffers::Offset<::flatbuffers::String> copyright) {
    fbb_.AddOffset(Exif::VT_COPYRIGHT, copyright);
  }
  void add_gpsaltituderef(::flatbuffers::Offset<::flatbuffers::String> gpsaltituderef) {
    fbb_.AddOffset(Exif::VT_GPSALTITUDEREF, gpsaltituderef);
  }
  void add_gpsdatestamp(::flatbuffers::Offset<::flatbuffers::String> gpsdatestamp) {
    fbb_.AddOffset(Exif::VT_GPSDATESTAMP, gpsdatestamp);
  }
  void add_gpslongitude(::flatbuffers::Offset<::flatbuffers::String> gpslongitude) {
    fbb_.AddOffset(Exif::VT_GPSLONGITUDE, gpslongitude);
  }
  void add_gpslatitude(::flatbuffers::Offset<::flatbuffers::String> gpslatitude) {
    fbb_.AddOffset(Exif::VT_GPSLATITUDE, gpslatitude);
  }
  void add_datetimeoriginal(::flatbuffers::Offset<::flatbuffers::String> datetimeoriginal) {
    fbb_.AddOffset(Exif::VT_DATETIMEORIGINAL, datetimeoriginal);
  }
  void add_securityclassification(::flatbuffers::Offset<::flatbuffers::String> securityclassification) {
    fbb_.AddOffset(Exif::VT_SECURITYCLASSIFICATION, securityclassification);
  }
  explicit ExifBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Exif> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Exif>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Exif> CreateExif(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> file_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> gpstag = 0,
    ::flatbuffers::Offset<::flatbuffers::String> imagedescription = 0,
    ::flatbuffers::Offset<::flatbuffers::String> gpslongituderef = 0,
    ::flatbuffers::Offset<::flatbuffers::String> gpsmapdatum = 0,
    ::flatbuffers::Offset<::flatbuffers::String> imageuniqueid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> imageid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> gpslatituderef = 0,
    ::flatbuffers::Offset<::flatbuffers::String> usercomment = 0,
    ::flatbuffers::Offset<::flatbuffers::String> gpsaltitude = 0,
    ::flatbuffers::Offset<::flatbuffers::String> documentname = 0,
    ::flatbuffers::Offset<::flatbuffers::String> gpstimestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::String> copyright = 0,
    ::flatbuffers::Offset<::flatbuffers::String> gpsaltituderef = 0,
    ::flatbuffers::Offset<::flatbuffers::String> gpsdatestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::String> gpslongitude = 0,
    ::flatbuffers::Offset<::flatbuffers::String> gpslatitude = 0,
    ::flatbuffers::Offset<::flatbuffers::String> datetimeoriginal = 0,
    ::flatbuffers::Offset<::flatbuffers::String> securityclassification = 0) {
  ExifBuilder builder_(_fbb);
  builder_.add_securityclassification(securityclassification);
  builder_.add_datetimeoriginal(datetimeoriginal);
  builder_.add_gpslatitude(gpslatitude);
  builder_.add_gpslongitude(gpslongitude);
  builder_.add_gpsdatestamp(gpsdatestamp);
  builder_.add_gpsaltituderef(gpsaltituderef);
  builder_.add_copyright(copyright);
  builder_.add_gpstimestamp(gpstimestamp);
  builder_.add_documentname(documentname);
  builder_.add_gpsaltitude(gpsaltitude);
  builder_.add_usercomment(usercomment);
  builder_.add_gpslatituderef(gpslatituderef);
  builder_.add_imageid(imageid);
  builder_.add_imageuniqueid(imageuniqueid);
  builder_.add_gpsmapdatum(gpsmapdatum);
  builder_.add_gpslongituderef(gpslongituderef);
  builder_.add_imagedescription(imagedescription);
  builder_.add_gpstag(gpstag);
  builder_.add_file_name(file_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Exif> CreateExifDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *file_name = nullptr,
    const char *gpstag = nullptr,
    const char *imagedescription = nullptr,
    const char *gpslongituderef = nullptr,
    const char *gpsmapdatum = nullptr,
    const char *imageuniqueid = nullptr,
    const char *imageid = nullptr,
    const char *gpslatituderef = nullptr,
    const char *usercomment = nullptr,
    const char *gpsaltitude = nullptr,
    const char *documentname = nullptr,
    const char *gpstimestamp = nullptr,
    const char *copyright = nullptr,
    const char *gpsaltituderef = nullptr,
    const char *gpsdatestamp = nullptr,
    const char *gpslongitude = nullptr,
    const char *gpslatitude = nullptr,
    const char *datetimeoriginal = nullptr,
    const char *securityclassification = nullptr) {
  auto file_name__ = file_name ? _fbb.CreateString(file_name) : 0;
  auto gpstag__ = gpstag ? _fbb.CreateString(gpstag) : 0;
  auto imagedescription__ = imagedescription ? _fbb.CreateString(imagedescription) : 0;
  auto gpslongituderef__ = gpslongituderef ? _fbb.CreateString(gpslongituderef) : 0;
  auto gpsmapdatum__ = gpsmapdatum ? _fbb.CreateString(gpsmapdatum) : 0;
  auto imageuniqueid__ = imageuniqueid ? _fbb.CreateString(imageuniqueid) : 0;
  auto imageid__ = imageid ? _fbb.CreateString(imageid) : 0;
  auto gpslatituderef__ = gpslatituderef ? _fbb.CreateString(gpslatituderef) : 0;
  auto usercomment__ = usercomment ? _fbb.CreateString(usercomment) : 0;
  auto gpsaltitude__ = gpsaltitude ? _fbb.CreateString(gpsaltitude) : 0;
  auto documentname__ = documentname ? _fbb.CreateString(documentname) : 0;
  auto gpstimestamp__ = gpstimestamp ? _fbb.CreateString(gpstimestamp) : 0;
  auto copyright__ = copyright ? _fbb.CreateString(copyright) : 0;
  auto gpsaltituderef__ = gpsaltituderef ? _fbb.CreateString(gpsaltituderef) : 0;
  auto gpsdatestamp__ = gpsdatestamp ? _fbb.CreateString(gpsdatestamp) : 0;
  auto gpslongitude__ = gpslongitude ? _fbb.CreateString(gpslongitude) : 0;
  auto gpslatitude__ = gpslatitude ? _fbb.CreateString(gpslatitude) : 0;
  auto datetimeoriginal__ = datetimeoriginal ? _fbb.CreateString(datetimeoriginal) : 0;
  auto securityclassification__ = securityclassification ? _fbb.CreateString(securityclassification) : 0;
  return Image::Metadatas::CreateExif(
      _fbb,
      file_name__,
      gpstag__,
      imagedescription__,
      gpslongituderef__,
      gpsmapdatum__,
      imageuniqueid__,
      imageid__,
      gpslatituderef__,
      usercomment__,
      gpsaltitude__,
      documentname__,
      gpstimestamp__,
      copyright__,
      gpsaltituderef__,
      gpsdatestamp__,
      gpslongitude__,
      gpslatitude__,
      datetimeoriginal__,
      securityclassification__);
}

struct Iptc FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IptcBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FILE_NAME = 4,
    VT_OBJECTNAME = 6,
    VT_COPYRIGHT = 8,
    VT_CAPTION = 10
  };
  const ::flatbuffers::String *file_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILE_NAME);
  }
  const ::flatbuffers::String *objectname() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OBJECTNAME);
  }
  const ::flatbuffers::String *copyright() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COPYRIGHT);
  }
  const ::flatbuffers::String *caption() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CAPTION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FILE_NAME) &&
           verifier.VerifyString(file_name()) &&
           VerifyOffset(verifier, VT_OBJECTNAME) &&
           verifier.VerifyString(objectname()) &&
           VerifyOffset(verifier, VT_COPYRIGHT) &&
           verifier.VerifyString(copyright()) &&
           VerifyOffset(verifier, VT_CAPTION) &&
           verifier.VerifyString(caption()) &&
           verifier.EndTable();
  }
};

struct IptcBuilder {
  typedef Iptc Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_file_name(::flatbuffers::Offset<::flatbuffers::String> file_name) {
    fbb_.AddOffset(Iptc::VT_FILE_NAME, file_name);
  }
  void add_objectname(::flatbuffers::Offset<::flatbuffers::String> objectname) {
    fbb_.AddOffset(Iptc::VT_OBJECTNAME, objectname);
  }
  void add_copyright(::flatbuffers::Offset<::flatbuffers::String> copyright) {
    fbb_.AddOffset(Iptc::VT_COPYRIGHT, copyright);
  }
  void add_caption(::flatbuffers::Offset<::flatbuffers::String> caption) {
    fbb_.AddOffset(Iptc::VT_CAPTION, caption);
  }
  explicit IptcBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Iptc> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Iptc>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Iptc> CreateIptc(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> file_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> objectname = 0,
    ::flatbuffers::Offset<::flatbuffers::String> copyright = 0,
    ::flatbuffers::Offset<::flatbuffers::String> caption = 0) {
  IptcBuilder builder_(_fbb);
  builder_.add_caption(caption);
  builder_.add_copyright(copyright);
  builder_.add_objectname(objectname);
  builder_.add_file_name(file_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Iptc> CreateIptcDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *file_name = nullptr,
    const char *objectname = nullptr,
    const char *copyright = nullptr,
    const char *caption = nullptr) {
  auto file_name__ = file_name ? _fbb.CreateString(file_name) : 0;
  auto objectname__ = objectname ? _fbb.CreateString(objectname) : 0;
  auto copyright__ = copyright ? _fbb.CreateString(copyright) : 0;
  auto caption__ = caption ? _fbb.CreateString(caption) : 0;
  return Image::Metadatas::CreateIptc(
      _fbb,
      file_name__,
      objectname__,
      copyright__,
      caption__);
}

struct Xmp FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef XmpBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FILE_NAME = 4,
    VT_COPYRIGHTOWNER = 6,
    VT_DOCUMENTNAME = 8,
    VT_ZIPCODE = 10,
    VT_LANGUAGE = 12,
    VT_COUNTRYCODE = 14,
    VT_LOCALADDRESS = 16,
    VT_SUBLOCATION = 18,
    VT_CATEGORY = 20,
    VT_PROVINCESTATE = 22,
    VT_CITY = 24,
    VT_IMAGEID = 26,
    VT_KEYWORDS = 28,
    VT_COUNTRYNAME = 30,
    VT_STREETNAME = 32,
    VT_RIGHTS = 34,
    VT_DESCRIPTION = 36,
    VT_TITLE = 38,
    VT_SUBJECT = 40,
    VT_SECURITYCLASSIFICATION = 42
  };
  const ::flatbuffers::String *file_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILE_NAME);
  }
  const ::flatbuffers::String *copyrightowner() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COPYRIGHTOWNER);
  }
  const ::flatbuffers::String *documentname() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DOCUMENTNAME);
  }
  const ::flatbuffers::String *zipcode() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ZIPCODE);
  }
  const ::flatbuffers::String *language() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LANGUAGE);
  }
  const ::flatbuffers::String *countrycode() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNTRYCODE);
  }
  const ::flatbuffers::String *localaddress() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LOCALADDRESS);
  }
  const ::flatbuffers::String *sublocation() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SUBLOCATION);
  }
  const ::flatbuffers::String *category() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CATEGORY);
  }
  const ::flatbuffers::String *provincestate() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROVINCESTATE);
  }
  const ::flatbuffers::String *city() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CITY);
  }
  const ::flatbuffers::String *imageid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IMAGEID);
  }
  const ::flatbuffers::String *keywords() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEYWORDS);
  }
  const ::flatbuffers::String *countryname() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNTRYNAME);
  }
  const ::flatbuffers::String *streetname() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STREETNAME);
  }
  const ::flatbuffers::String *rights() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RIGHTS);
  }
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  const ::flatbuffers::String *title() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TITLE);
  }
  const ::flatbuffers::String *subject() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SUBJECT);
  }
  const ::flatbuffers::String *securityclassification() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SECURITYCLASSIFICATION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FILE_NAME) &&
           verifier.VerifyString(file_name()) &&
           VerifyOffset(verifier, VT_COPYRIGHTOWNER) &&
           verifier.VerifyString(copyrightowner()) &&
           VerifyOffset(verifier, VT_DOCUMENTNAME) &&
           verifier.VerifyString(documentname()) &&
           VerifyOffset(verifier, VT_ZIPCODE) &&
           verifier.VerifyString(zipcode()) &&
           VerifyOffset(verifier, VT_LANGUAGE) &&
           verifier.VerifyString(language()) &&
           VerifyOffset(verifier, VT_COUNTRYCODE) &&
           verifier.VerifyString(countrycode()) &&
           VerifyOffset(verifier, VT_LOCALADDRESS) &&
           verifier.VerifyString(localaddress()) &&
           VerifyOffset(verifier, VT_SUBLOCATION) &&
           verifier.VerifyString(sublocation()) &&
           VerifyOffset(verifier, VT_CATEGORY) &&
           verifier.VerifyString(category()) &&
           VerifyOffset(verifier, VT_PROVINCESTATE) &&
           verifier.VerifyString(provincestate()) &&
           VerifyOffset(verifier, VT_CITY) &&
           verifier.VerifyString(city()) &&
           VerifyOffset(verifier, VT_IMAGEID) &&
           verifier.VerifyString(imageid()) &&
           VerifyOffset(verifier, VT_KEYWORDS) &&
           verifier.VerifyString(keywords()) &&
           VerifyOffset(verifier, VT_COUNTRYNAME) &&
           verifier.VerifyString(countryname()) &&
           VerifyOffset(verifier, VT_STREETNAME) &&
           verifier.VerifyString(streetname()) &&
           VerifyOffset(verifier, VT_RIGHTS) &&
           verifier.VerifyString(rights()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffset(verifier, VT_TITLE) &&
           verifier.VerifyString(title()) &&
           VerifyOffset(verifier, VT_SUBJECT) &&
           verifier.VerifyString(subject()) &&
           VerifyOffset(verifier, VT_SECURITYCLASSIFICATION) &&
           verifier.VerifyString(securityclassification()) &&
           verifier.EndTable();
  }
};

struct XmpBuilder {
  typedef Xmp Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_file_name(::flatbuffers::Offset<::flatbuffers::String> file_name) {
    fbb_.AddOffset(Xmp::VT_FILE_NAME, file_name);
  }
  void add_copyrightowner(::flatbuffers::Offset<::flatbuffers::String> copyrightowner) {
    fbb_.AddOffset(Xmp::VT_COPYRIGHTOWNER, copyrightowner);
  }
  void add_documentname(::flatbuffers::Offset<::flatbuffers::String> documentname) {
    fbb_.AddOffset(Xmp::VT_DOCUMENTNAME, documentname);
  }
  void add_zipcode(::flatbuffers::Offset<::flatbuffers::String> zipcode) {
    fbb_.AddOffset(Xmp::VT_ZIPCODE, zipcode);
  }
  void add_language(::flatbuffers::Offset<::flatbuffers::String> language) {
    fbb_.AddOffset(Xmp::VT_LANGUAGE, language);
  }
  void add_countrycode(::flatbuffers::Offset<::flatbuffers::String> countrycode) {
    fbb_.AddOffset(Xmp::VT_COUNTRYCODE, countrycode);
  }
  void add_localaddress(::flatbuffers::Offset<::flatbuffers::String> localaddress) {
    fbb_.AddOffset(Xmp::VT_LOCALADDRESS, localaddress);
  }
  void add_sublocation(::flatbuffers::Offset<::flatbuffers::String> sublocation) {
    fbb_.AddOffset(Xmp::VT_SUBLOCATION, sublocation);
  }
  void add_category(::flatbuffers::Offset<::flatbuffers::String> category) {
    fbb_.AddOffset(Xmp::VT_CATEGORY, category);
  }
  void add_provincestate(::flatbuffers::Offset<::flatbuffers::String> provincestate) {
    fbb_.AddOffset(Xmp::VT_PROVINCESTATE, provincestate);
  }
  void add_city(::flatbuffers::Offset<::flatbuffers::String> city) {
    fbb_.AddOffset(Xmp::VT_CITY, city);
  }
  void add_imageid(::flatbuffers::Offset<::flatbuffers::String> imageid) {
    fbb_.AddOffset(Xmp::VT_IMAGEID, imageid);
  }
  void add_keywords(::flatbuffers::Offset<::flatbuffers::String> keywords) {
    fbb_.AddOffset(Xmp::VT_KEYWORDS, keywords);
  }
  void add_countryname(::flatbuffers::Offset<::flatbuffers::String> countryname) {
    fbb_.AddOffset(Xmp::VT_COUNTRYNAME, countryname);
  }
  void add_streetname(::flatbuffers::Offset<::flatbuffers::String> streetname) {
    fbb_.AddOffset(Xmp::VT_STREETNAME, streetname);
  }
  void add_rights(::flatbuffers::Offset<::flatbuffers::String> rights) {
    fbb_.AddOffset(Xmp::VT_RIGHTS, rights);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(Xmp::VT_DESCRIPTION, description);
  }
  void add_title(::flatbuffers::Offset<::flatbuffers::String> title) {
    fbb_.AddOffset(Xmp::VT_TITLE, title);
  }
  void add_subject(::flatbuffers::Offset<::flatbuffers::String> subject) {
    fbb_.AddOffset(Xmp::VT_SUBJECT, subject);
  }
  void add_securityclassification(::flatbuffers::Offset<::flatbuffers::String> securityclassification) {
    fbb_.AddOffset(Xmp::VT_SECURITYCLASSIFICATION, securityclassification);
  }
  explicit XmpBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Xmp> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Xmp>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Xmp> CreateXmp(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> file_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> copyrightowner = 0,
    ::flatbuffers::Offset<::flatbuffers::String> documentname = 0,
    ::flatbuffers::Offset<::flatbuffers::String> zipcode = 0,
    ::flatbuffers::Offset<::flatbuffers::String> language = 0,
    ::flatbuffers::Offset<::flatbuffers::String> countrycode = 0,
    ::flatbuffers::Offset<::flatbuffers::String> localaddress = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sublocation = 0,
    ::flatbuffers::Offset<::flatbuffers::String> category = 0,
    ::flatbuffers::Offset<::flatbuffers::String> provincestate = 0,
    ::flatbuffers::Offset<::flatbuffers::String> city = 0,
    ::flatbuffers::Offset<::flatbuffers::String> imageid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> keywords = 0,
    ::flatbuffers::Offset<::flatbuffers::String> countryname = 0,
    ::flatbuffers::Offset<::flatbuffers::String> streetname = 0,
    ::flatbuffers::Offset<::flatbuffers::String> rights = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    ::flatbuffers::Offset<::flatbuffers::String> title = 0,
    ::flatbuffers::Offset<::flatbuffers::String> subject = 0,
    ::flatbuffers::Offset<::flatbuffers::String> securityclassification = 0) {
  XmpBuilder builder_(_fbb);
  builder_.add_securityclassification(securityclassification);
  builder_.add_subject(subject);
  builder_.add_title(title);
  builder_.add_description(description);
  builder_.add_rights(rights);
  builder_.add_streetname(streetname);
  builder_.add_countryname(countryname);
  builder_.add_keywords(keywords);
  builder_.add_imageid(imageid);
  builder_.add_city(city);
  builder_.add_provincestate(provincestate);
  builder_.add_category(category);
  builder_.add_sublocation(sublocation);
  builder_.add_localaddress(localaddress);
  builder_.add_countrycode(countrycode);
  builder_.add_language(language);
  builder_.add_zipcode(zipcode);
  builder_.add_documentname(documentname);
  builder_.add_copyrightowner(copyrightowner);
  builder_.add_file_name(file_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Xmp> CreateXmpDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *file_name = nullptr,
    const char *copyrightowner = nullptr,
    const char *documentname = nullptr,
    const char *zipcode = nullptr,
    const char *language = nullptr,
    const char *countrycode = nullptr,
    const char *localaddress = nullptr,
    const char *sublocation = nullptr,
    const char *category = nullptr,
    const char *provincestate = nullptr,
    const char *city = nullptr,
    const char *imageid = nullptr,
    const char *keywords = nullptr,
    const char *countryname = nullptr,
    const char *streetname = nullptr,
    const char *rights = nullptr,
    const char *description = nullptr,
    const char *title = nullptr,
    const char *subject = nullptr,
    const char *securityclassification = nullptr) {
  auto file_name__ = file_name ? _fbb.CreateString(file_name) : 0;
  auto copyrightowner__ = copyrightowner ? _fbb.CreateString(copyrightowner) : 0;
  auto documentname__ = documentname ? _fbb.CreateString(documentname) : 0;
  auto zipcode__ = zipcode ? _fbb.CreateString(zipcode) : 0;
  auto language__ = language ? _fbb.CreateString(language) : 0;
  auto countrycode__ = countrycode ? _fbb.CreateString(countrycode) : 0;
  auto localaddress__ = localaddress ? _fbb.CreateString(localaddress) : 0;
  auto sublocation__ = sublocation ? _fbb.CreateString(sublocation) : 0;
  auto category__ = category ? _fbb.CreateString(category) : 0;
  auto provincestate__ = provincestate ? _fbb.CreateString(provincestate) : 0;
  auto city__ = city ? _fbb.CreateString(city) : 0;
  auto imageid__ = imageid ? _fbb.CreateString(imageid) : 0;
  auto keywords__ = keywords ? _fbb.CreateString(keywords) : 0;
  auto countryname__ = countryname ? _fbb.CreateString(countryname) : 0;
  auto streetname__ = streetname ? _fbb.CreateString(streetname) : 0;
  auto rights__ = rights ? _fbb.CreateString(rights) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto title__ = title ? _fbb.CreateString(title) : 0;
  auto subject__ = subject ? _fbb.CreateString(subject) : 0;
  auto securityclassification__ = securityclassification ? _fbb.CreateString(securityclassification) : 0;
  return Image::Metadatas::CreateXmp(
      _fbb,
      file_name__,
      copyrightowner__,
      documentname__,
      zipcode__,
      language__,
      countrycode__,
      localaddress__,
      sublocation__,
      category__,
      provincestate__,
      city__,
      imageid__,
      keywords__,
      countryname__,
      streetname__,
      rights__,
      description__,
      title__,
      subject__,
      securityclassification__);
}

inline const Image::Metadatas::Picture *GetPicture(const void *buf) {
  return ::flatbuffers::GetRoot<Image::Metadatas::Picture>(buf);
}

inline const Image::Metadatas::Picture *GetSizePrefixedPicture(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Image::Metadatas::Picture>(buf);
}

inline const char *PictureIdentifier() {
  return "PLUG";
}

inline bool PictureBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, PictureIdentifier());
}

inline bool SizePrefixedPictureBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, PictureIdentifier(), true);
}

inline bool VerifyPictureBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Image::Metadatas::Picture>(PictureIdentifier());
}

inline bool VerifySizePrefixedPictureBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Image::Metadatas::Picture>(PictureIdentifier());
}

inline void FinishPictureBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Image::Metadatas::Picture> root) {
  fbb.Finish(root, PictureIdentifier());
}

inline void FinishSizePrefixedPictureBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Image::Metadatas::Picture> root) {
  fbb.FinishSizePrefixed(root, PictureIdentifier());
}

}  // namespace Metadatas
}  // namespace Image

#endif  // FLATBUFFERS_GENERATED_RZWRITEFLATBUFFERS_IMAGE_METADATAS_H_
